#!/bin/bash

function traverse() {
  for dir in $1/*
  do
    if [ -d "${dir}" ] ; then
      echo "updating $dir"
      cd "$dir"
      gsync
    fi
  done
}

cd ~
echo "restoring ~"
gsync

cd ~/.config
echo "restoring ~/.config"
gsync

cd ~/.local/bin
echo "restoring ~/.local/bin"
gsync

echo "restoring Github repos"
traverse ~/Documents/github

echo "restoring Bitbucket repos"
traverse ~/Documents/bitbucket
