#!/bin/bash

function traverse() {
  for dir in $1/*
  do
    if [ -d "${dir}" ] ; then
      echo "updating $dir"
      cd "$dir"
      gsync
    fi
  done
}

cd ~
echo "syncing ~"
gsync

cd ~/.config
echo "syncing ~/.config"
gsync

cd ~/.local/bin
echo "syncing ~/.local/bin"
gsync

echo "syncing Github repos"
traverse ~/Documents/github

echo "syncing Bitbucket repos"
traverse ~/Documents/bitbucket
